#!/bin/bash
set -e

CMD=$1

case $CMD in
    "" | help)
        echo "Usage: $0 <command>
        
Commands:
  help    Show this help message
  run     Run the development Django server in Python venv
        "
        ;;
    run)
        cd "${0%/*}/backend"
        if [[ ! -f ".env" ]]; then
            echo "No .env file found. Please create one."
            exit 1
        fi
        if [[ ! -d "./venv" ]]; then
            virtualenv venv
        fi
        source venv/bin/activate
        pip install -r requirements.txt 
        python manage.py runserver
        ;;
esac
exit 0
