services:
  backend:
    container_name: backend
    image: premade-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    ports:
      - 8000:8000
    environment:
      DEBUG: 'True'

  frontend:
    container_name: frontend
    image: premade-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: yarn start
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development